
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const here = path.dirname(fileURLToPath(import.meta.url));
const assetsDir = path.resolve(here, "../assets");
const files = ["favicon.ico", "robots.txt", "css/site.css", "js/editor.js", "js/site.js", "js/paranote.js", "js/admin.js"];
const out = [];
out.push("// GENERATED by scripts/build-assets.mjs — do not edit by hand.");
out.push("// Embeds the static assets so the Worker can be deployed as a single file (no assets binding).");
out.push("export const STATIC_MAP: Record<string, { type: string; body: string; isBinary?: boolean }> = {");
for (const f of files) {
  const p = path.join(assetsDir, f);
  if (!fs.existsSync(p)) { console.error("missing asset", f); process.exit(1); }
  const raw = fs.readFileSync(p);
  const type = f.endsWith(".css") ? "text/css; charset=utf-8" : f.endsWith(".js") ? "application/javascript; charset=utf-8" : f === "favicon.ico" ? "image/x-icon" : f === "robots.txt" ? "text/plain; charset=utf-8" : "application/octet-stream";
  const isBinary = f === "favicon.ico";
  out.push('  "/' + f + '": { type: "' + type + '", body: "' + (isBinary ? raw.toString("base64") : raw.toString("utf8").replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")) + '"' + (isBinary ? ", isBinary: true" : "") + " },");
}
out.push("};");
fs.writeFileSync(path.resolve(here, "../src/static.ts"), out.join("\n") + "\n");
console.log("src/static.ts generated (" + files.length + " assets)");
